version: '3.9'

volumes:
  geoserver-data:
  geo-db-data:


services:
  db:
    image: kartoza/postgis:${POSTGIS_VERSION_TAG}
    volumes:
      - geo-db-data:/var/lib/postgresql
    networks:
      - geoserver
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=POSTGRES
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
      - FORCE_SSL=FALSE
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U docker -d gis"
    restart: always

  geoserver:
    image: kartoza/geoserver:${GS_VERSION}
    volumes:
      - type: bind
        source: /mnt/data/GEOSERVER_DATA
        target: /opt/data/geoserver_data
      - type: bind
        source: /media/Data
        target: /opt/data/coastal6_data
      - type: bind
        source: /mnt/data/GEOSERVER_CACHE
        target: /opt/data/geoserver_cache
      - type: bind
        source: /mnt/data/postgresql
        target: /var/lib/postgresql
      - type: bind
        source: /home/skyler8/docker-geoserver/build_data/web.xml
        target: /settings/web.xml
    networks:
      - geoserver
    ports:
      - ${GEOSERVER_PORT}:8080
    environment:
      - GEOSERVER_DATA_DIR=/opt/data/geoserver_data
      - GEOWEBCACHE_CACHE_DIR=/opt/data/geoserver_cache
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
      - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "geoserver"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: always

networks:
  geoserver:
    name: geoserver
    external: true
